### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by SameerShanbhogue** [kchemorion/slicerGUI#1]
Hi @kchemorion

How to persist installed extension after exiting and re-launching Slicer. The installed extensions disappear after re-launch.

Thanks
Sameer

**Comment by kchemorion** [comment]
Hi @SameerShanbhogue ,

Thanks for reaching out. If you want the extensions to persist then you need to persist the configuration found at: /root/.config/NA-MIC/Slicer.ini. Let me know if this works.
